name: sketchy_retrieval
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pytorch::pytorch
  - pytorch::torchvision
  - pip
  - pip:
      - transformers==4.46.3
      - accelerate
      - pillow
      - tqdm
      - sentencepiece
